  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: black
        name: Format files with black
        language: system
        entry: uv run black --preview
        require_serial: true
        types_or: [python, pyi]
      - id: ruff-lint
        name: Lint files with ruff
        entry: uv run ruff check
        language: system
        require_serial: true
        types_or: [python, pyi, jupyter]
        args:
          - --fix
          - --show-fixes
          - --force-exclude
